import { Link } from "wouter";
import Navigation from "@/components/Navigation";
import { ArrowRight, BookOpen, Droplets, Globe2, Lightbulb, Recycle, Sprout, Sun, TreePine } from "lucide-react";

const sdgs = [
  { number: 6, title: "Clean Water", text: "Protect water and understand the systems that keep communities healthy.", icon: Droplets, color: "text-cyan-600" },
  { number: 7, title: "Clean Energy", text: "Explore reliable, affordable, and sustainable energy choices.", icon: Sun, color: "text-amber-600" },
  { number: 11, title: "Sustainable Cities", text: "Imagine inclusive, resilient places designed for people and planet.", icon: Globe2, color: "text-blue-600" },
  { number: 12, title: "Responsible Consumption", text: "Rethink materials, reduce waste, and keep resources in use.", icon: Recycle, color: "text-emerald-600" },
  { number: 13, title: "Climate Action", text: "Build evidence-based understanding and take meaningful climate action.", icon: Sprout, color: "text-green-700" },
  { number: 15, title: "Life on Land", text: "Value biodiversity and help nature recover where you live and learn.", icon: TreePine, color: "text-lime-700" },
];

export default function Learn() {
  return <div className="min-h-screen bg-background"><Navigation /><main className="container px-6 pb-20 pt-12 md:pt-20"><section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Learn with purpose</p><h1 className="mt-3 text-4xl font-black tracking-tight md:text-6xl">Understand the systems behind impact.</h1><p className="mt-6 text-lg leading-relaxed text-muted-foreground">Start with a question, connect it to an SDG, and choose a mission that turns understanding into action.</p></section><section className="mt-14"><div className="flex items-end justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Sustainable Development Goals</p><h2 className="mt-2 text-3xl font-black">Explore the SDGs</h2></div><BookOpen className="h-7 w-7 text-primary" /></div><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{sdgs.map(({ number, title, text, icon: Icon, color }) => <article key={number} className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className={`flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 ${color}`}><Icon className="h-6 w-6" /></div><p className="mt-6 text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">SDG {number}</p><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p><Link href="/missions"><span className="mt-5 inline-flex cursor-pointer items-center gap-2 text-sm font-semibold text-primary">Find a mission <ArrowRight className="h-4 w-4" /></span></Link></article>)}</div></section><section className="mt-14 rounded-2xl border border-border bg-card p-8"><h2 className="text-2xl font-black">Continue learning</h2><p className="mt-3 max-w-2xl text-muted-foreground">Use the existing guides, rubrics, FAQs, and toolkits when you need deeper support for an investigation or creative response.</p><Link href="/resources"><span className="mt-6 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Open learning resources <ArrowRight className="h-4 w-4" /></span></Link></section></main></div>;
}
